In [3]:
import numpy as np
#Definimos la matriz T
T=np.array([[0,1/10,-1/5,0],[1/11,0,1/11,-3/11],[-1/5,1/10,0,1/10],[0,-3/8,1/8,0]])
c=np.array([3/5,25/11,-11/10,15/8])
x=np.array([0,0,0,0]) #Vector de valores iniciales
erroraceptado=0.0005
error=1
iteraciones=0
maxiter=int(input('introduzca numero de iteraciones'))
print('Iteraciones')
print("      x1           x2          x3          x4")
while error>erroraceptado and iteraciones<maxiter:
    resultado=np.dot(T,x)+c
    print(resultado)
    numerador=np.amax(abs((resultado-x)))
    denominador=np.amax(abs(resultado))
    error=numerador/denominador
    x=resultado
print()
print()
print('los valores buscados que dan solucion son:')
print("      x1           x2          x3          x4")
print('iteracion: ',iteraciones,resultado)

introduzca numero de iteraciones15
Iteraciones
      x1           x2          x3          x4
[ 0.6         2.27272727 -1.1         1.875     ]
[ 1.04727273  1.71590909 -0.80522727  0.88522727]
[ 0.93263636  2.05330579 -1.04934091  1.13088068]
[ 1.01519876  1.95369576 -0.96810863  0.97384272]
[ 0.9889913   2.01141473 -1.0102859   1.02135051]
[ 1.00319865  1.99224126 -0.99452174  0.99443374]
[ 0.99812847  2.00230688 -1.00197223  1.00359431]
[ 1.00062513  1.9986703  -0.99903558  0.99888839]
[ 0.99967415  2.00044767 -1.00036916  1.00061919]
[ 1.0001186   1.99976795 -0.99982814  0.99978598]


los valores buscados que dan solucion son:
      x1           x2          x3          x4
[ 1.0001186   1.99976795 -0.99982814  0.99978598]
